import { db } from "@/lib/db";

// GET /api/rooms/[code]/ledger-pdf?memberId=xxx
// Returns a simple text-based ledger (the browser can save it as a file)
// Note: For a real PDF, we'd use a library like jsPDF, but to keep dependencies
// minimal, we return a formatted text report that can be downloaded.
export async function GET(req: Request, { params }: { params: Promise<{ code: string }> }) {
  try {
    const { code } = await params;
    const url = new URL(req.url);
    const memberId = url.searchParams.get("memberId");

    if (!memberId) return new Response("memberId required", { status: 400 });

    const room = await db.room.findUnique({ where: { code: code.toUpperCase() } });
    if (!room) return new Response("Room not found", { status: 404 });

    const member = await db.roomMember.findFirst({ where: { id: memberId, roomId: room.id } });
    if (!member) return new Response("Member not found", { status: 404 });

    const isMinister = member.role === "minister" || member.email === room.hostEmail;
    if (!isMinister) return new Response("Only minister can export ledger", { status: 403 });

    const incidents = await db.kelaIncident.findMany({
      where: { roomId: room.id, verdict: { not: "pending" } },
      orderBy: { createdAt: "desc" },
      include: {
        user: { select: { name: true, email: true, ratePerKela: true } },
        accusedBy: { select: { name: true } },
      },
    });

    const members = await db.roomMember.findMany({
      where: { roomId: room.id, status: "approved" },
      orderBy: { name: "asc" },
    });

    // Build a CSV-like text report
    let report = `KELA TRACKER - FINE LEDGER\n`;
    report += `Room: ${room.name} (${room.code})\n`;
    report += `Generated: ${new Date().toLocaleString()}\n`;
    report += `Generated by: ${member.name}\n`;
    report += `${"=".repeat(60)}\n\n`;

    // Summary per member
    report += `SUMMARY BY MEMBER\n`;
    report += `${"-".repeat(60)}\n`;
    report += `Name                 | Kelas | Rate  | Gross Fine | Paid    | Balance\n`;
    report += `${"-".repeat(60)}\n`;

    for (const m of members) {
      const mIncidents = incidents.filter((i) => i.userId === m.id && i.verdict === "kela");
      const guilty = mIncidents.length;
      const gross = mIncidents.reduce((s, i) => s + (i.rateAtTime || m.ratePerKela), 0);
      const paid = mIncidents.reduce((s, i) => s + (i.paidAmount || 0), 0);
      const balance = gross - paid;
      report += `${m.name.padEnd(20)} | ${String(guilty).padStart(5)} | ${String(m.ratePerKela).padStart(5)} | ${String(gross).padStart(10)} | ${String(paid).padStart(7)} | ${String(balance).padStart(7)}\n`;
    }

    report += `\n${"=".repeat(60)}\n\n`;

    // All incidents
    report += `ALL INCIDENTS (most recent first)\n`;
    report += `${"-".repeat(60)}\n`;
    report += `Date                | Accused           | Verdict | Rate | Paid | Reason\n`;
    report += `${"-".repeat(60)}\n`;

    for (const inc of incidents) {
      const date = new Date(inc.createdAt).toLocaleDateString();
      const rate = inc.rateAtTime || inc.user.ratePerKela;
      const reason = (inc.reason || "").slice(0, 30);
      report += `${date.padEnd(18)} | ${inc.user.name.padEnd(17)} | ${inc.verdict.padEnd(7)} | ${String(rate).padStart(4)} | ${String(inc.paidAmount || 0).padStart(4)} | ${reason}\n`;
    }

    report += `\n${"=".repeat(60)}\n`;
    report += `Total incidents: ${incidents.length}\n`;
    report += `Total members: ${members.length}\n`;

    return new Response(report, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="kela-ledger-${room.code}-${new Date().toISOString().split("T")[0]}.txt"`,
      },
    });
  } catch (e: any) {
    return new Response("Server error", { status: 500 });
  }
}
